---
name: smart_shipment_system
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.4
  flutter_phoenix: ^1.1.1
  shared_preferences: ^2.2.2
  get_it: ^7.6.7
  go_router: ^13.2.0
  dartz: ^0.10.1
  dio: ^5.4.1
  animated_splash_screen: ^1.3.0
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.4
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.0
  loader_overlay: ^4.0.0
  rxdart: ^0.27.7
  page_transition: ^2.1.0
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.5
  image_picker: ^1.1.0
  firebase_core: ^2.30.1
  google_maps_flutter: ^2.6.1
  firebase_storage: ^11.7.7
  location: ^6.0.1
  flutter_polyline_points: ^2.0.0
  open_street_map_search_and_pick: ^0.1.1
  flutter_animate: ^4.5.0
  day_picker: ^2.2.0
  json_annotation: ^4.9.0
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.1
  flutter_hooks: ^0.20.5
  firebase_app_check: ^0.2.2+7
  cached_network_image: ^3.3.1
  animated_bottom_navigation_bar: ^1.3.3
  animated_rating_stars: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/json/
  - assets/translations/
  - assets/icons/
  - assets/SVGs/
  fonts:
  - family: Inter
    fonts:
    - asset: assets/fonts/Inter-Black.ttf
      weight: 900
    - asset: assets/fonts/Inter-Bold.ttf
      weight: 700
    - asset: assets/fonts/Inter-ExtraBold.ttf
      weight: 800
    - asset: assets/fonts/Inter-ExtraLight.ttf
      weight: 200
    - asset: assets/fonts/Inter-Light.ttf
      weight: 300
    - asset: assets/fonts/Inter-Medium.ttf
      weight: 500
    - asset: assets/fonts/Inter-Regular.ttf
      weight: 400
    - asset: assets/fonts/Inter-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/Inter-Thin.ttf
      weight: 100
  - family: Rubik
    fonts:
    - asset: assets/fonts/Rubik-Black.ttf
      weight: 900
    - asset: assets/fonts/Rubik-BlackItalic.ttf
      weight: 900
    - asset: assets/fonts/Rubik-Bold.ttf
      weight: 700
    - asset: assets/fonts/Rubik-ExtraBold.ttf
      weight: 800
    - asset: assets/fonts/Rubik-ExtraBoldItalic.ttf
      weight: 800
    - asset: assets/fonts/Rubik-Light.ttf
      weight: 300
    - asset: assets/fonts/Rubik-LightItalic.ttf
      weight: 300
    - asset: assets/fonts/Rubik-Italic.ttf
      weight: 300
    - asset: assets/fonts/Rubik-Medium.ttf
      weight: 500
    - asset: assets/fonts/Rubik-MediumItalic.ttf
      weight: 500
    - asset: assets/fonts/Rubik-Regular.ttf
      weight: 400
    - asset: assets/fonts/Rubik-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/Rubik-SemiBoldItalic.ttf
      weight: 600